# Yaml code for creating a deployment and service of backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: assignment2-backend

spec:
  replicas: 3
  selector:
    matchLabels:
      app: assignment2-backend
  
  template:
    metadata:
      labels:
        app: assignment2-backend
    spec:
      containers:
        - name: backendcontainer
          image: muqeem/assignment2-kubernetes-backend:latest
          ports:
           - containerPort: 5000
          env:
            MONGO_URI: "mongodb://mongodb-service/mernAuthentication"

---
# Yaml for making the external service for backend deployment
apiVersion: v1
kind: Service
metadata:
  name: backend-service

spec:
  type: NodePort
  selector:
    app: assignment2-backend

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30200
